### ISSUE TITLE
o kasi ala e nasin UCSUR a

### ISSUE THREAD

**Issue by ibnz36** [gregdan3/ilo-pi-toki-pona-taso#1]
ilo li kaasi e nasin UCSUR. taso la nasin ni li toki pona kin
![image](https://github.com/gregdan3/ilo-pi-toki-pona-taso/assets/73384214/8b2855b0-1e90-4acd-bd70-9fc930b6a9cf)
(jan toki lon sitelen ni^ li mi ala)

**Comment by gregdan3** [comment]
a, mi sona e pakala ni. mi pona e ni lon tenpo poka. nasin li nasa.

taso, pakala li lon ilo pi sona toki: https://github.com/gregdan3/sona-toki

**Comment by ibnz36** [comment]
a, sona

**Comment by gregdan3** [comment]
mi pona e ni.
